services:
  axonserver:
    image: axoniq/axonserver
    container_name: axon_gateway_axon_server
    ports:
      - "8024:8024"
      - "8124:8124"
    environment:
      AXONIQ_AXONSERVER_DEVMODE_ENABLED: "true"
      AXONIQ_AXONSERVER_STANDALONE: "true"
