<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.toolisticon.maven.parent</groupId>
    <artifactId>maven-parent-kotlin-base</artifactId>
    <version>2025.6.0</version>
    <relativePath />
  </parent>

  <name>Axon Framework - Gateway Extension - Parent</name>
  <description>Extension for Axon Framework that provides additional gateways.</description>
  <url>https://github.com/holixon/axon-gateway-extension/</url>

  <groupId>io.holixon.axon.gateway</groupId>
  <artifactId>axon-gateway-extension-parent</artifactId>
  <version>2.1.1-SNAPSHOT</version>
  <packaging>pom</packaging>

  <modules>
    <module>extension/core</module>
    <module>extension/spring-boot-autoconfigure</module>
    <module>extension/spring-boot-starter</module>
    <module>extension/jackson-module</module>
  </modules>

  <properties>
    <axon.version>4.11.3</axon.version>
    <springboot.version>3.5.4</springboot.version>
  </properties>

  <dependencyManagement>
    <dependencies>

      <!-- Project dependencies -->
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>axon-gateway-extension</artifactId>
        <version>${project.version}</version>
      </dependency>

      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>axon-gateway-spring-boot-autoconfigure</artifactId>
        <version>${project.version}</version>
      </dependency>

      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>axon-gateway-spring-boot-starter</artifactId>
        <version>${project.version}</version>
      </dependency>

      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>axon-gateway-jackson-module</artifactId>
        <version>${project.version}</version>
      </dependency>

      <!-- second: SpringBoot Import -->
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${springboot.version}</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>

      <dependency>
        <groupId>org.axonframework</groupId>
        <artifactId>axon-bom</artifactId>
        <version>${axon.version}</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>

      <dependency>
        <groupId>io.mockk</groupId>
        <artifactId>mockk-jvm</artifactId>
        <version>1.14.2</version>
        <scope>test</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib</artifactId>
    </dependency>
  </dependencies>

  <build>
      <plugins>
        <!-- Kotlin Compile -->
        <plugin>
          <groupId>org.jetbrains.kotlin</groupId>
          <artifactId>kotlin-maven-plugin</artifactId>
          <configuration>
            <compilerPlugins>
              <plugin>no-arg</plugin>
              <plugin>spring</plugin>
              <plugin>all-open</plugin>
            </compilerPlugins>
            <pluginOptions>
              <!-- Axon specific classes -->
              <option>all-open:annotation=org.axonframework.modelling.command.AggregateRoot</option>
            </pluginOptions>
          </configuration>
        </plugin>
      </plugins>
  </build>

  <profiles>
    <profile>
      <!--
      Example module, should be skipped during release
      -->
      <id>example</id>
      <activation>
        <property>
          <name>!skipExamples</name>
        </property>
      </activation>
      <modules>
        <module>example</module>
      </modules>
    </profile>
  </profiles>

  <!-- deploy and release configuration -->
  <distributionManagement>
    <site>
      <id>README</id>
      <url>https://github.com/holixon/axon-gateway-extension</url>
    </site>
  </distributionManagement>

  <scm>
    <connection>scm:git:git://github.com/holixon/axon-gateway-extension.git</connection>
    <developerConnection>scm:git:git@github.com:holixon/axon-gateway-extension.git
    </developerConnection>
    <url>https://github.com/holixon/axon-gateway-extension</url>
    <tag>HEAD</tag>
  </scm>

  <issueManagement>
    <system>GitHub</system>
    <url>https://github.com/holixon/axon-gateway-extension/issues</url>
  </issueManagement>

  <!-- License Stuff -->
  <inceptionYear>2020</inceptionYear>
  <licenses>
    <license>
      <name>Apache 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0</url>
    </license>
  </licenses>
  <organization>
    <name>Holisticon AG</name>
    <url>https://holixon.io</url>
  </organization>

</project>
