server:
  port: 8079

axon-gateway:
  query:
    type: revision-aware
    revision-aware:
      default-query-timeout: 10_000

axon:
  gateway:
    version: '@axon.version@'
  framework:
    version: '@project.version@'
