name: Development Build and Tests

on:
  push:
    branches:
      - '*'
      - '**/*'
      - '!master'
      - '!release/*'

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build and tests on JDK ${{ matrix.java }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache .m2
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11.0.5

      - name: Prepare Maven Wrapper
        run: chmod +x ./mvnw

      - name: Prepare Maven Wrapper
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw clean verify -U -B -T4
