name: Development Build and Tests

on:
  push:
    branches:
      - '*'
      - '**/*'
      - '!master'
      - '!release/*'

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build and tests on JDK ${{ matrix.java }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11.0.5
          cache: 'maven'

      - name: Prepare Maven Wrapper
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw clean verify -U -B -T4

      - name: Upload coverage to Codecov
        if: github.event_name == 'push' && github.actor != 'dependabot[bot]'
        uses: codecov/codecov-action@v3
        with:
          token: "${{secrets.CODECOV_TOKEN}}"

      - name: Upload test coverage to Codacy
        if: github.event_name == 'push' && github.actor != 'dependabot[bot]'
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh)
        env:
          CODACY_PROJECT_TOKEN: "${{secrets.CODACY_PROJECT_TOKEN}}"
